pipeline {
    agent {
        any {
            image 'node:lts-buster-slim'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('OWASP Dependancy'){
            steps{
                dependencyCheck additionalArguments: '--noupdate --format HTML --format XML --disableYarnAudit', odcInstallation: 'Default'   
            }
        }
    }
    post {
        success{
                dependencyCheckPublisher pattern: 'dependency-check-report.xml'      
        }
    }
}
